name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Ensure Mocha is executable
        run: chmod +x ./node_modules/.bin/mocha

      - name: Clean up any processes on port 3001
        run: |
          lsof -t -i:3001 | xargs kill -9 || true

      - name: Start the server in background
        run: |
          PORT=3001 nohup node server.js > server.log 2>&1 &

      - name: Wait for server to be available
        run: |
          while ! nc -z localhost 3001; do
            echo "Waiting for server to start..."
            sleep 1
          done
          echo "Server is up and running."

      - name: Run tests
        run: npm test

      - name: Stop the server
        run: |
          kill $(lsof -t -i:3001) || true

      - name: Build Docker image
        run: |
          docker build -t ghilesbesseghir039469/pipeline:latest .
          docker images  # Optional: display Docker images for verification

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ghilesbesseghir039469/pipeline:latest

      - name: Display server logs
        run: cat server.log
        if: failure()  # Display logs only if previous steps fail
