name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Ensure Mocha is executable
        run: chmod +x ./node_modules/.bin/mocha

      - name: Start the server in background
        run: |
          nohup node server.js > server.log 2>&1 &

      - name: Wait for server to start
        run: |
          sleep 10 # Adjust sleep duration if needed
          curl --silent --fail http://localhost:3000 > /dev/null

      - name: Run tests
        run: npm test

      - name: Stop the server
        run: |
          kill $(lsof -t -i:3000) || true

      - name: Build Docker image
        run: |
          docker build -t ghilesbesseghir039469/pipeline:latest .
          docker images  # Optional: display Docker images for verification

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ghilesbesseghir039469/pipeline:latest
